### ISSUE TITLE
add callpoint to clean up stuff before the RestBCAdapter times out

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/RestBridge#7]
add a callpoint to clean up stuff, like removing locks, logbook entries etc.. This should probably be executed before the release in line 64:

call authpgm$+"::ON_CLEANUP",err=*next

and the authenticate.bbj should get a dummy label ON_CLEANUP to demonstrate the behavior for newbies. (Does it have ON_REQUEST, does it have sufficient REM - please check at that occasion)

**Comment by SebastianAdams** [comment]
Fixed in the Version 1.03
