### ISSUE TITLE
Replace the public plug-in description

### ISSUE THREAD

**Issue by RalphLance** [BBj-Plugins/RestBridge#9]
Replace the public plug-in description seen in the Plugin Manager Launcher to at least what is in the readme:

"This plugin allows you to deploy BBj or Java classes that follow the development paradigm of "BusinessComponents" as a RESTful web service. It features GET,POST,PUT,DELETE operations that are automatically translated to read, write and remove methods in your code."

**Comment by SebastianAdams** [comment]
Updated the plug-in description in the version 1.11
